### ISSUE TITLE
HelloWorld has jerky horizontal mouse movement (vertical is fine) on neko/cpp on Linux

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel-templates#31]
Flixel 4.0.0, 4.2.0, and git (from yesterday) with openfl 3.6.1, lime 2.9.1, on Linux Mint 18.1 MATE x64, with haxe 3.4.0.

HelloWorld template, unmodified, on neko and cpp both (in release mode) look like this:

![flixel helloworld neko](https://cloud.githubusercontent.com/assets/16719964/22507643/cd23c6f0-e886-11e6-86d6-9042b28e29e2.gif)

Hopefully despite it being a gif you can tell the stark difference in feeling between the vertical and horizontal mouse movement.  Compare with horizontal outside the window, where it's smooth again.  Inside it visually resembles "snap to grid" except that the grid has irregular spacing.

**Comment by Gama11** [comment]
flixel-templates is not the correct place to report this.

**Comment by IBwWG** [comment]
@Gama11 I was going to report it to flixel, but, for example, on Lars' actions__ branch of git, his FlxAction demo does not display this issue.

Besides, a "you're wrong" is less helpful than "what is right is: X".

**Comment by Gama11** [comment]
Reporting this issue here implies something is wrong with the template that is causing this issue. I don't see any evidence for that, perhaps it's an issue with "empty projects" in general for instance?

Besides, pretty much all demos are created from this template, probably inculding Lars' FlxActions demo, so that doesn't make much sense. ;)

**Comment by IBwWG** [comment]
OK, if it's an issue with empty projects in general, and that's what flixel-templates provides, and it's not an issue with flixel, because other flixel projects don't have this issue, then...?

**Comment by Gama11** [comment]
Tbh, this sort of low-level / OS-specific thing rarely is a Flixel issue to begin with. Maybe Lime, but it's hard to make that claim without isolating it. And even if we managed that, reporting issues for Lime 2.9.1 would be a bit silly at this point...

**Comment by IBwWG** [comment]
How can it be a lime issue?  Again, other flixel projects (hey, they use lime too) work fine.

Also I'm surprised you just said that reporting issues for lime 2.9.1 is silly.  If so then flixel should bump its lime dependency, no?

**Comment by IBwWG** [comment]
Also how should I know that it's OS-specific?  Have you verified that?

**Comment by Gama11** [comment]
>How can it be a lime issue? Again, other flixel projects (hey, they use lime too) work fine.

Over the time, you get a feeling for what sort of issues are Flixel issues and what issues are OpenFL/Lime or even Haxe. The cursor is an OpenFL Sprite, mouse events are provided by Lime / OpenFL... Flixel really doesn't do much here that could cause any issues. Of course, I could be wrong.

>Also how should I know that it's OS-specific? Have you verified that?

Somehow the issue sounded OS-specific to me. I guess you didn't really say that though.

>Also I'm surprised you just said that reporting issues for lime 2.9.1 is silly.

Well, there won't be any more bugfixes for Lime 2.x / Lime legacy. Of course, it's possible that the latest Lime release also has the issue, in which case it should be reported, but that has to be checked first.

>If so then flixel should bump its lime dependency, no?

Well, [we're working on that](https://github.com/HaxeFlixel/flixel/pull/2032), turns out it's not so simple... :/

**Comment by IBwWG** [comment]
Regarding OS specificity I just verified it myself, but I'd still like to know why you assumed that.

Or how a lime issue would not affect other, more complicated flixel projects.

Usually it's the other way around, it's tricky getting a bare-bones example...

**Comment by IBwWG** [comment]
I later reproduced it on a Linux VM under a Windows host for flixel 4.0.0 and actions__, but not 4.2.0.  Lime version steady at 2.9.1 throughout.  So I think you were right about OS (well, it was also only on 64-bit...I tried 32-bit and could not repro on flixel 4.0.0) but not about flixel vs. lime.

The thing is, if there's a problem, and the lime version is stuck right now, which is understandably quite a big thing, then there should be some process for that.  If it was lime-specific, and there's no patch, there's still a point in reporting it, because:

1. the next person who comes along and finds things broken may at least find that it's a bug, and it's not because they're not using the tools correctly => less confusion
1. when the lime version bump *does* happen, it can be verified whether the bug is still there with the latest flixel+lime officially supported combination

I think point 1 is important in terms of PR, and point 2 is important in terms of QA.
